### ISSUE TITLE
V5

### ISSUE THREAD

**Issue by danielwerg** [danielwerg/r6api.js#97]
- [ ] ESM bullshittery
  - Use ESM?
    - Support CJS as well?
    - Using `.js` extension for `.ts` files are dumb (solution: https://github.com/justkey007/tsc-alias ?)
  - Stick with CJS?
    - Drop hacky ESM support?
- [ ] Drop method for `playerstats2/statistics` endpoint and write little guide how to implement custom method for historical stats (https://github.com/danielwerg/r6api.js/issues/78, https://github.com/danielwerg/r6api.js/issues/47) (low priority)
- [x] Multiple instances (https://github.com/danielwerg/r6api.js/issues/71)
- [ ] `prod.datadev.ubisoft.com` methods (https://github.com/danielwerg/r6api.js/issues/42)
- [x] Implement `profiles/gamesplayed` endpoint (https://github.com/danielwerg/r6api.js/issues/81https://github.com/danielwerg/r6api.js/issues/81)
- [ ] Rename "user" to "profile" where needed in methods?
- readme
  - [ ] Better method description

**Comment by danielwerg** [comment]
By "Drop hacky ESM support?" I'm referencing https://github.com/danielwerg/r6api.js/pull/70 @BadCoder1337 👀

**Comment by BadCoder1337** [comment]
> By "Drop hacky ESM support?" I'm referencing #70 @BadCoder1337 👀

IMHO ESM isn't accepted enough to drop CJS. I am not authoring any npm library so can't give final advice, but think guys from https://github.com/sapphiredev/framework doing well. Their project compiles to CJS and wraps with
https://github.com/addaleax/gen-esm-wrapper to support ESM.

**Comment by BadCoder1337** [comment]
> Rename "user" to "profile" where needed in methods

IMHO There's two ways of naming we could stick to:
1) Keep names close to Ubisoft as possible (e.g. `PlatformCrossplay` => `PlatformFamilies` )
2) Choose different names for consistency and compatibility reasons ? (e.g. unified rank info interface for all seasons. Fetching data before Operation Health - `prod.datadev.ubisoft.com`, Health to Brutal Swarm - `r6karma/players`, Solar Raid - `r6s/skill/full_profiles`)

**Comment by danielwerg** [comment]
@EndBug I realized I haven't added ts-utils to V5 that you have added while ago in this commit https://github.com/danielwerg/r6api.js/commit/0d599ac4823d449a0e6270da28c43a45bbe8c276. Could you give me quick ted talk why we need them and how you use them?

**Comment by EndBug** [comment]
@danielwerg If I remember well, I added it because they help when validating user input, when you need to check whether the input is a valid operator, weapon, etc.

**Comment by danielwerg** [comment]
Hey @BadCoder1337, I published new repo - [R6Data](https://github.com/danielwerg/r6data), which is going to be a dependency of next version of R6API.js and I used [gen-esm-wrapper](https://github.com/addaleax/gen-esm-wrapper) for ESM support. Could you test it in your ESM environment and let me know if you have any issue with it?
